Add nvcr based fips compliant dockerfile
uc-cdis/containers pull request #142
Opened 2024-01-03 22:46 UTC by nss10

* Add a new Dockerfile to include a non-anibali based fips-compliant docker file

2024-01-04 03:21 UTC, aartivnkt requested changes
just tested the image in the containers repo, this one: `gen3-cuda-11.8-ubuntu22.04-openssl` -- somehow it still returns 3.0.2 for openSSL library
```
OpenSSL 3.0.8 7 Feb 2023 (Library: OpenSSL 3.0.2 15 Mar 2022)
```

2024-01-26 20:13 UTC, xiao-uofc commented
corrected env variable here.

2024-01-26 20:15 UTC, xiao-uofc reviewed
correct env variable applied here.

2024-01-26 21:35 UTC, aartivnkt approved these changes

2024-01-26 21:35 UTC, merged